//
//  AddNewWords.swift
//  Verbs.Hebrew
//
//  Created by Anton Rubenchik on 01/03/2019.
//  Copyright © 2019 Anton Rubenchik. All rights reserved.
//

import Foundation
class AddNewWords {
    //    let newWordsArray : [BlackWord] = []
    //
    let newWordsArray : [BlackWord] = [
        BlackWord(translation  : "drop, knock over, let drop; leave land uncultivated (bibl.)",
                  infinitive   : "לִשְׁמוֹטlishmot",
                  presentMS    : "שׁוֹמֵטshomet",
                  presentFS: "שׁוֹמֶטֶתshometet",
                  presentMP: "שׁוֹמְטִיםshomtim",
                  presentFP: "שׁוֹמְטוֹתshomtot",
                  past1S: "שָׁמַטְתִּיshamateti",
                  past2MS: "שָׁמַטְתָּshamateta",
                  past2FS: "שָׁמַטְתְּshamatet",
                  past3MS: "שָׁמַטshamat",
                  past3FS: "שָׁמְטָהshamta",
                  past1P: "שָׁמַטְנוּshamatnu",
                  past2MP: "*שְׁמַטְתֶּםshmatetem",
                  past2FP: "*שְׁמַטְתֶּןshmateten",
                  past3P: "שָׁמְטוּshamtu",
                  future1S: "אֶשְׁמוֹטeshmot",
                  future2MS: "תִּשְׁמוֹטtishmot",
                  future2FS: "תִּשְׁמְטִיtishmeti",
                  future3MS: "יִשְׁמוֹטyishmot",
                  future3FS: "תִּשְׁמוֹטtishmot",
                  future1P: "נִשְׁמוֹטnishmot",
                  future2MP: "תִּשְׁמְטוּtishmetu",
                  future2FP: "תִּשְׁמְטוּtishmetu",
                  future3MP: "יִשְׁמְטוּyishmetu",
                  future3FP: "יִשְׁמְטוּyishmetu",
                  imperativeMS: "שְׁמוֹט!‏shmot!",
                  imperativeFS: "שִׁמְטִי!‏shimti!",
                  imperativeMP: "שִׁמְטוּ!‏shimtu!",
                  imperativeFP: "שִׁמְטוּ!‏shimtu!"),
        BlackWord(translation  : "become fatter, fatten",
                  infinitive   : "לִשְׁמוֹןlishmon",
                  presentMS    : "שָׁמֵןshamen",
                  presentFS: "שְׁמֵנָהshmena",
                  presentMP: "שְׁמֵנִיםshmenim",
                  presentFP: "שְׁמֵנוֹתshmenot",
                  past1S: "שָׁמַנְתִּיshamanti",
                  past2MS: "שָׁמַנְתָּshamanta",
                  past2FS: "שָׁמַנְתְּshamant",
                  past3MS: "שָׁמַןshaman",
                  past3FS: "שָׁמְנָהshamna",
                  past1P: "שָׁמַנּוּshamannu",
                  past2MP: "*שְׁמַנְתֶּםshmantem",
                  past2FP: "*שְׁמַנְתֶּןshmanten",
                  past3P: "שָׁמְנוּshamnu",
                  future1S: "אֶשְׁמַןeshman",
                  future2MS: "תִּשְׁמַןtishman",
                  future2FS: "תִּשְׁמְנִיtishmeni",
                  future3MS: "יִשְׁמַןyishman",
                  future3FS: "תִּשְׁמַןtishman",
                  future1P: "נִשְׁמַןnishman",
                  future2MP: "תִּשְׁמְנוּtishmenu",
                  future2FP: "תִּשְׁמְנוּtishmenu",
                  future3MP: "יִשְׁמְנוּyishmenu",
                  future3FP: "יִשְׁמְנוּyishmenu",
                  imperativeMS: "",
                  imperativeFS: "",
                  imperativeMP: "",
                  imperativeFP: ""),
        BlackWord(translation  : "hear; listen",
                  infinitive   : "לִשְׁמוֹעַlishmoa",
                  presentMS    : "שׁוֹמֵעַshomea",
                  presentFS: "שׁוֹמַעַתshoma'at",
                  presentMP: "שׁוֹמְעִיםshom'im",
                  presentFP: "שׁוֹמְעוֹתshom'ot",
                  past1S: "שָׁמַעְתִּיshamati",
                  past2MS: "שָׁמַעְתָּshamata",
                  past2FS: "שָׁמַעְתְּshamat",
                  past3MS: "שָׁמַעshama",
                  past3FS: "שָׁמְעָהsham'a",
                  past1P: "שָׁמַעְנוּshamanu",
                  past2MP: "*שְׁמַעְתֶּםshma'atem",
                  past2FP: "*שְׁמַעְתֶּןshma'aten",
                  past3P: "שָׁמְעוּsham'u",
                  future1S: "אֶשְׁמַעeshma",
                  future2MS: "תִּשְׁמַעtishma",
                  future2FS: "תִּשְׁמְעִיtishme'i",
                  future3MS: "יִשְׁמַעyishma",
                  future3FS: "תִּשְׁמַעtishma",
                  future1P: "נִשְׁמַעnishma",
                  future2MP: "תִּשְׁמְעוּtishme'u",
                  future2FP: "תִּשְׁמְעוּtishme'u",
                  future3MP: "יִשְׁמְעוּyishme'u",
                  future3FP: "יִשְׁמְעוּyishme'u",
                  imperativeMS: "שְׁמַע!‏shma!",
                  imperativeFS: "שִׁמְעִי!‏shim'i!",
                  imperativeMP: "שִׁמְעוּ!‏shim'u!",
                  imperativeFP: "שִׁמְעוּ!‏shim'u!"),
        BlackWord(translation  : "be ruined, abandoned (biblical)",
                  infinitive   : "לָשׁוֹםlashom",
                  presentMS    : "שׁוֹמֵםshomem",
                  presentFS: "שׁוֹמֶמֶתshomemet",
                  presentMP: "שׁוֹמְמִיםshomemim",
                  presentFP: "שׁוֹמְמוֹתshomemot",
                  past1S: "שָׁמַמְתִּיshamamti",
                  past2MS: "שָׁמַמְתָּshamamta",
                  past2FS: "שָׁמַמְתְּshamamt",
                  past3MS: "שָׁמֵםshamem",
                  past3FS: "שָׁמְמָהshamema",
                  past1P: "שָׁמַמְנוּshamamnu",
                  past2MP: "*שְׁמַמְתֶּםshmamtem",
                  past2FP: "*שְׁמַמְתֶּןshmamten",
                  past3P: "שָׁמְמוּshamemu",
                  future1S: "אֵשַׁםesham",
                  future2MS: "תֵּשַׁםtesham",
                  future2FS: "תֵּשַׁמִּיteshami",
                  future3MS: "יֵשַׁםyesham",
                  future3FS: "תֵּשַׁםtesham",
                  future1P: "נֵשַׁםnesham",
                  future2MP: "תֵּשַׁמּוּteshamu",
                  future2FP: "תֵּשַׁמּוּteshamu",
                  future3MP: "יֵשַׁמּוּyeshamu",
                  future3FP: "יֵשַׁמּוּyeshamu",
                  imperativeMS: "שׁוֹם!‏shom!",
                  imperativeFS: "שׁוֹמִּי!‏shomi!",
                  imperativeMP: "שׁוֹמּוּ!‏shomu!",
                  imperativeFP: "שׁוֹמּוּ!‏shomu!"),
    ]

  
  
   
}

/*
 let newWordsArray : [BlackWord] = [
 BlackWord(translation  : "ронять, склонять (голову); оставлять землю необработанной ",
 infinitive   : "לִשְׁמוֹטлишмот",
 presentMS    : "שׁוֹמֵטшомет",
 presentFS: "שׁוֹמֶטֶתшометет",
 presentMP: "שׁוֹמְטִיםшомтим",
 presentFP: "שׁוֹמְטוֹתшомтот",
 past1S: "שָׁמַטְתִּיшаматети",
 past2MS: "שָׁמַטְתָּшаматета",
 past2FS: "שָׁמַטְתְּшаматет",
 past3MS: "שָׁמַטшамат",
 past3FS: "שָׁמְטָהшамта",
 past1P: "שָׁמַטְנוּшаматну",
 past2MP: "*שְׁמַטְתֶּםшматетем",
 past2FP: "*שְׁמַטְתֶּןшматетен",
 past3P: "שָׁמְטוּшамту",
 future1S: "אֶשְׁמוֹטэшмот",
 future2MS: "תִּשְׁמוֹטтишмот",
 future2FS: "תִּשְׁמְטִיтишмети",
 future3MS: "יִשְׁמוֹטйишмот",
 future3FS: "תִּשְׁמוֹטтишмот",
 future1P: "נִשְׁמוֹטнишмот",
 future2MP: "תִּשְׁמְטוּтишмету",
 future2FP: "תִּשְׁמְטוּтишмету",
 future3MP: "יִשְׁמְטוּйишмету",
 future3FP: "יִשְׁמְטוּйишмету",
 imperativeMS: "שְׁמוֹט!‏шмот!",
 imperativeFS: "שִׁמְטִי!‏шимти!",
 imperativeMP: "שִׁמְטוּ!‏шимту!",
 imperativeFP: "שִׁמְטוּ!‏шимту!"),
 BlackWord(translation  : "быть разрушенным, покинутым (библ.)",
 infinitive   : "לָשׁוֹםлашом",
 presentMS    : "שׁוֹמֵםшомем",
 presentFS: "שׁוֹמֶמֶתшомемет",
 presentMP: "שׁוֹמְמִיםшомемим",
 presentFP: "שׁוֹמְמוֹתшомемот",
 past1S: "שָׁמַמְתִּיшамамти",
 past2MS: "שָׁמַמְתָּшамамта",
 past2FS: "שָׁמַמְתְּшамамт",
 past3MS: "שָׁמֵםшамем",
 past3FS: "שָׁמְמָהшамема",
 past1P: "שָׁמַמְנוּшамамну",
 past2MP: "*שְׁמַמְתֶּםшмамтем",
 past2FP: "*שְׁמַמְתֶּןшмамтен",
 past3P: "שָׁמְמוּшамему",
 future1S: "אֶשּׁוֹםэшом",
 future2MS: "תִּישּׁוֹםтишом",
 future2FS: "תִּישְּׁמִיтишми",
 future3MS: "יִישּׁוֹםйишом",
 future3FS: "תִּישּׁוֹםтишом",
 future1P: "נִישּׁוֹםнишом",
 future2MP: "תִּישְּׁמוּтишму",
 future2FP: "תִּישְּׁמוּтишму",
 future3MP: "יִישְּׁמוּйишму",
 future3FP: "יִישְּׁמוּйишму",
 imperativeMS: "שׁוֹם!‏шом!",
 imperativeFS: "שׁוֹמִּי!‏шоми!",
 imperativeMP: "שׁוֹמּוּ!‏шому!",
 imperativeFP: "שׁוֹמּוּ!‏шому!"),
 BlackWord(translation  : "жиреть, толстеть",
 infinitive   : "לִשְׁמוֹןлишмон",
 presentMS    : "שָׁמֵןшамен",
 presentFS: "שְׁמֵנָהшмена",
 presentMP: "שְׁמֵנִיםшменим",
 presentFP: "שְׁמֵנוֹתшменот",
 past1S: "שָׁמַנְתִּיшаманти",
 past2MS: "שָׁמַנְתָּшаманта",
 past2FS: "שָׁמַנְתְּшамант",
 past3MS: "שָׁמַןшаман",
 past3FS: "שָׁמְנָהшамна",
 past1P: "שָׁמַנּוּшаманну",
 past2MP: "*שְׁמַנְתֶּםшмантем",
 past2FP: "*שְׁמַנְתֶּןшмантен",
 past3P: "שָׁמְנוּшамну",
 future1S: "אֶשְׁמַןэшман",
 future2MS: "תִּשְׁמַןтишман",
 future2FS: "תִּשְׁמְנִיтишмени",
 future3MS: "יִשְׁמַןйишман",
 future3FS: "תִּשְׁמַןтишман",
 future1P: "נִשְׁמַןнишман",
 future2MP: "תִּשְׁמְנוּтишмену",
 future2FP: "תִּשְׁמְנוּтишмену",
 future3MP: "יִשְׁמְנוּйишмену",
 future3FP: "יִשְׁמְנוּйишмену",
 imperativeMS: "",
 imperativeFS: "",
 imperativeMP: "",
 imperativeFP: ""),
 BlackWord(translation  : "слышать; слушать",
 infinitive   : "לִשְׁמוֹעַлишмоа",
 presentMS    : "שׁוֹמֵעַшомеа",
 presentFS: "שׁוֹמַעַתшомаат",
 presentMP: "שׁוֹמְעִיםшомъим",
 presentFP: "שׁוֹמְעוֹתшомъот",
 past1S: "שָׁמַעְתִּיшамати",
 past2MS: "שָׁמַעְתָּшамата",
 past2FS: "שָׁמַעְתְּшамат",
 past3MS: "שָׁמַעшама",
 past3FS: "שָׁמְעָהшамъа",
 past1P: "שָׁמַעְנוּшаману",
 past2MP: "*שְׁמַעְתֶּםшмаатем",
 past2FP: "*שְׁמַעְתֶּןшмаатен",
 past3P: "שָׁמְעוּшамъу",
 future1S: "אֶשְׁמַעэшма",
 future2MS: "תִּשְׁמַעтишма",
 future2FS: "תִּשְׁמְעִיтишмеи",
 future3MS: "יִשְׁמַעйишма",
 future3FS: "תִּשְׁמַעтишма",
 future1P: "נִשְׁמַעнишма",
 future2MP: "תִּשְׁמְעוּтишмеу",
 future2FP: "תִּשְׁמְעוּтишмеу",
 future3MP: "יִשְׁמְעוּйишмеу",
 future3FP: "יִשְׁמְעוּйишмеу",
 imperativeMS: "שְׁמַע!‏шма!",
 imperativeFS: "שִׁמְעִי!‏шимъи!",
 imperativeMP: "שִׁמְעוּ!‏шимъу!",
 imperativeFP: "שִׁמְעוּ!‏шимъу!")
 ]
 */
